apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-03-02T12:46:26Z"
  generation: 1
  labels:
    app: sample-code3
  name: sample-code3
  namespace: default
  resourceVersion: "13920"
  uid: 2dd36988-d750-4108-a2a9-fc815fbd7b63
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sample-code3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sample-code3
    spec:
      containers:
      - image: amanmishra98/nodejs_code_main:27
        imagePullPolicy: IfNotPresent
        name: nodejs-code-main-kvz98
        volumeMounts:
          - name: azure
            mountPath: /var/www/html
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: azure
          persistentVolumeClaim:
            claimName: azurefile
